apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName  }}
    spec:
      containers:
        - name: {{ .Values.applicationName }}
          imagePullPolicy: Always
          image: asia-east1-docker.pkg.dev/mypoc-374706/apps-repo/java-app:IMAGE
          ports:
            - containerPort: 80
