apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: {{ .Values.applicationName }}
  type: NodePort
  selector:
    app: {{ .Values.applicationName }}
